Regenerated.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP build build_cpu build_vendor build_os host host_cpu host_vendor host_os PLATFORM LN_S ECHO RANLIB ac_ct_RANLIB EGREP LIBTOOL FAULT_CONTEXT FAULT_CONTEXT_INCLUDE HAVE_SIGSEGV_RECOVERY HAVE_STACK_OVERFLOW_RECOVERY RELOCATABLE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP build build_cpu build_vendor build_os host host_cpu host_vendor host_os PLATFORM LN_S ECHO RANLIB ac_ct_RANLIB EGREP LIBTOOL FAULT_CONTEXT FAULT_CONTEXT_INCLUDE HAVE_SIGSEGV_RECOVERY CFG_STACKVMA HAVE_STACK_OVERFLOW_RECOVERY CFG_LEAVE CFG_HANDLER RELOCATABLE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -8078,7 +8078,7 @@ done
 
 
 case "$host_os" in
-  sunos4* | freebsd*)
+  sunos4* | freebsd* | openbsd* | netbsd*)
     CFG_SIGNALS=signals-bsd.h ;;
   hpux*)
     CFG_SIGNALS=signals-hpux.h ;;
@@ -9321,7 +9321,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 
 #include <signal.h>
 #include <asm/sigcontext.h>
-#include "src/fault-linux-m68k.c"
+#include "$srcdir/src/fault-linux-m68k.c"
 void sigsegv_handler (int sig, int code, struct sigcontext *scp)
 {
   void *fault_address = (void *) (get_fault_addr (scp));
@@ -9374,7 +9374,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 # include <sys/signal.h>
 #endif
 #include <asm/sigcontext.h>
-#include "src/fault-linux-m68k.c"
+#include "$srcdir/src/fault-linux-m68k.c"
 #include <sys/types.h>
 #include <sys/mman.h>
 #if HAVE_MMAP_DEVZERO
@@ -10579,6 +10579,187 @@ echo "${ECHO_T}$sv_cv_fault_osf_alpha" >&6
 
 
 
+  echo "$as_me:$LINENO: checking whether a fault handler according to NetBSD Alpha works" >&5
+echo $ECHO_N "checking whether a fault handler according to NetBSD Alpha works... $ECHO_C" >&6
+if test "${sv_cv_fault_netbsd_alpha+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+    if test "$cross_compiling" = yes; then
+  case "$host" in
+         alpha*-*-osf[4-9]* | alpha-*-*bsd*) sv_cv_fault_netbsd_alpha=yes ;;
+         *)
+           cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <signal.h>
+#include "$srcdir/src/fault-netbsd-alpha.c"
+void sigsegv_handler (int sig, int code, struct sigcontext *scp)
+{
+  void *fault_address = (void *) (get_fault_addr (scp));
+}
+
+int
+main ()
+{
+struct sigaction action;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sv_cv_fault_netbsd_alpha="guessing no"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+sv_cv_fault_netbsd_alpha=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+           ;;
+       esac
+
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <stdlib.h>
+#include <signal.h>
+#if HAVE_SYS_SIGNAL_H
+# include <sys/signal.h>
+#endif
+#include "$srcdir/src/fault-netbsd-alpha.c"
+#include <sys/types.h>
+#include <sys/mman.h>
+#if HAVE_MMAP_DEVZERO
+# include <fcntl.h>
+# ifndef MAP_FILE
+#  define MAP_FILE 0
+# endif
+#endif
+#ifndef PROT_NONE
+# define PROT_NONE 0
+#endif
+#if HAVE_MMAP_ANON
+# define zero_fd -1
+# define map_flags MAP_ANON | MAP_PRIVATE
+#elif HAVE_MMAP_ANONYMOUS
+# define zero_fd -1
+# define map_flags MAP_ANONYMOUS | MAP_PRIVATE
+#elif HAVE_MMAP_DEVZERO
+static int zero_fd;
+# define map_flags MAP_FILE | MAP_PRIVATE
+#endif
+unsigned long page;
+int handler_called = 0;
+void sigsegv_handler (int sig, int code, struct sigcontext *scp)
+{
+  void *fault_address = (void *) (get_fault_addr (scp));
+  handler_called++;
+  if (fault_address != (void*)(page + 0x678))
+    exit (3);
+  if (mprotect ((void *) page, 0x10000, PROT_READ | PROT_WRITE) < 0)
+    exit (2);
+}
+void crasher (unsigned long p)
+{
+  *(int *) (p + 0x678) = 42;
+}
+int main ()
+{
+  void *p;
+  struct sigaction action;
+  /* Preparations.  */
+#if !HAVE_MMAP_ANON && !HAVE_MMAP_ANONYMOUS && HAVE_MMAP_DEVZERO
+  zero_fd = open ("/dev/zero", O_RDONLY, 0644);
+#endif
+  /* Setup some mmaped memory.  */
+#ifdef __hpux
+  /* HP-UX 10 mmap() often fails when given a hint.  So give the OS complete
+     freedom about the address range.  */
+  p = mmap ((void *) 0,          0x10000, PROT_READ | PROT_WRITE, map_flags, zero_fd, 0);
+#else
+  p = mmap ((void *) 0x12340000, 0x10000, PROT_READ | PROT_WRITE, map_flags, zero_fd, 0);
+#endif
+  if (p == (void *)(-1))
+    exit (2);
+  page = (unsigned long) p;
+  /* Make it read-only.  */
+  if (mprotect ((void *) page, 0x10000, PROT_READ) < 0)
+    exit (2);
+  /* Install the SIGSEGV handler.  */
+  sigemptyset(&action.sa_mask);
+
+  action.sa_handler = (void (*) (int)) &sigsegv_handler;
+  action.sa_flags = 0;
+
+  sigaction (SIGSEGV, &action, (struct sigaction *) NULL);
+  sigaction (SIGBUS, &action, (struct sigaction *) NULL);
+  /* The first write access should invoke the handler and then complete.  */
+  crasher (page);
+  /* The second write access should not invoke the handler.  */
+  crasher (page);
+  /* Check that the handler was called only once.  */
+  if (handler_called != 1)
+    exit (1);
+  /* Test passed!  */
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sv_cv_fault_netbsd_alpha=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+sv_cv_fault_netbsd_alpha=no
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+fi
+echo "$as_me:$LINENO: result: $sv_cv_fault_netbsd_alpha" >&5
+echo "${ECHO_T}$sv_cv_fault_netbsd_alpha" >&6
+
+
+
+
+
+
   echo "$as_me:$LINENO: checking whether a fault handler according to AIX works" >&5
 echo $ECHO_N "checking whether a fault handler according to AIX works... $ECHO_C" >&6
 if test "${sv_cv_fault_aix+set}" = set; then
@@ -10779,7 +10960,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
 #include <signal.h>
-#include "src/fault-macos-powerpc.c"
+#include "$srcdir/src/fault-macos-powerpc.c"
 void sigsegv_handler (int sig, int code, struct sigcontext *scp)
 {
   void *fault_address = (void *) (get_fault_addr (scp));
@@ -10831,7 +11012,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 #if HAVE_SYS_SIGNAL_H
 # include <sys/signal.h>
 #endif
-#include "src/fault-macos-powerpc.c"
+#include "$srcdir/src/fault-macos-powerpc.c"
 #include <sys/types.h>
 #include <sys/mman.h>
 #if HAVE_MMAP_DEVZERO
@@ -11146,6 +11327,12 @@ if test -z "$CFG_FAULT" && test "$sv_cv_fault_osf_alpha" = yes; then
   case "$host_cpu" in
     alpha*) CFG_FAULT=fault-osf-alpha.h ;;
     *) CFG_FAULT=fault-osf.h ;;
+  esac
+  FAULT_CONTEXT='struct sigcontext'
+fi
+if test -z "$CFG_FAULT" && test "$sv_cv_fault_netbsd_alpha" = yes; then
+  case "$host_cpu" in
+    alpha*) CFG_FAULT=fault-netbsd-alpha.h ;;
   esac
   FAULT_CONTEXT='struct sigcontext'
 fi
@@ -11525,6 +11712,7 @@ fi
 cat >>confdefs.h <<_ACEOF
 #define CFG_STACKVMA "$CFG_STACKVMA"
 _ACEOF
+
 
 
 
@@ -11924,16 +12112,16 @@ if test "${sv_cv_have_stack_overflow_recovery+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
-      if test "$sv_cv_sigaltstack" != no; then
-    sv_cv_have_stack_overflow_recovery=yes
+        if test "$sv_cv_sigaltstack" != no; then
+    sv_cv_have_stack_overflow_recovery=maybe
   else
     case "$host_os" in
-      beos*) sv_cv_have_stack_overflow_recovery=yes ;;
+      beos*) sv_cv_have_stack_overflow_recovery=maybe ;;
       mingw* | cygwin*) sv_cv_have_stack_overflow_recovery=yes ;;
       *) sv_cv_have_stack_overflow_recovery=no ;;
     esac
   fi
-  if test $sv_cv_have_stack_overflow_recovery = yes; then
+  if test $sv_cv_have_stack_overflow_recovery = maybe; then
     if test -n "$CFG_FAULT"; then
       cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
@@ -11943,7 +12131,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-#include "src/$CFG_FAULT"
+#include "$srcdir/src/$CFG_FAULT"
 #ifdef SIGSEGV_FAULT_HANDLER_ARGLIST
 #ifdef SIGSEGV_FAULT_ADDRESS
 xyzzy
@@ -11971,7 +12159,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-#include "src/$CFG_FAULT"
+#include "$srcdir/src/$CFG_FAULT"
 #ifdef SIGSEGV_FAULT_HANDLER_ARGLIST
 #ifdef SIGSEGV_FAULT_STACKPOINTER
 xyzzy
@@ -12791,6 +12979,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
+
 case "$host_os" in
   mingw* | cygwin*) CFG_HANDLER=handler-win32.c ;;
   *)
@@ -12806,6 +12995,7 @@ esac
 cat >>confdefs.h <<_ACEOF
 #define CFG_HANDLER "$CFG_HANDLER"
 _ACEOF
+
 
 
 { echo; echo "${term_bold}Build Parameters:${term_norm}"; } >& 6
@@ -13527,7 +13717,10 @@ s,@LIBTOOL@,$LIBTOOL,;t t
 s,@FAULT_CONTEXT@,$FAULT_CONTEXT,;t t
 s,@FAULT_CONTEXT_INCLUDE@,$FAULT_CONTEXT_INCLUDE,;t t
 s,@HAVE_SIGSEGV_RECOVERY@,$HAVE_SIGSEGV_RECOVERY,;t t
+s,@CFG_STACKVMA@,$CFG_STACKVMA,;t t
 s,@HAVE_STACK_OVERFLOW_RECOVERY@,$HAVE_STACK_OVERFLOW_RECOVERY,;t t
+s,@CFG_LEAVE@,$CFG_LEAVE,;t t
+s,@CFG_HANDLER@,$CFG_HANDLER,;t t
 s,@RELOCATABLE@,$RELOCATABLE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
