Regenerated.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9665,6 +9665,186 @@ echo "${ECHO_T}$sv_cv_fault_linux_powerpc" >&6
 
 
 
+  echo "$as_me:$LINENO: checking whether a fault handler according to Linux/HPPA works" >&5
+echo $ECHO_N "checking whether a fault handler according to Linux/HPPA works... $ECHO_C" >&6
+if test "${sv_cv_fault_linux_hppa+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+    if test "$cross_compiling" = yes; then
+  case "$host" in
+
+         *)
+           cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <signal.h>
+
+void sigsegv_handler (int sig, siginfo_t *sip, void *ucp)
+{
+  void *fault_address = (void *) (sip->si_ptr);
+}
+
+int
+main ()
+{
+struct sigaction action;
+action.sa_sigaction = &sigsegv_handler;
+   action.sa_flags = SA_SIGINFO;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sv_cv_fault_linux_hppa="guessing no"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+sv_cv_fault_linux_hppa=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+           ;;
+       esac
+
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <stdlib.h>
+#include <signal.h>
+#if HAVE_SYS_SIGNAL_H
+# include <sys/signal.h>
+#endif
+
+#include <sys/types.h>
+#include <sys/mman.h>
+#if HAVE_MMAP_DEVZERO
+# include <fcntl.h>
+# ifndef MAP_FILE
+#  define MAP_FILE 0
+# endif
+#endif
+#ifndef PROT_NONE
+# define PROT_NONE 0
+#endif
+#if HAVE_MMAP_ANON
+# define zero_fd -1
+# define map_flags MAP_ANON | MAP_PRIVATE
+#elif HAVE_MMAP_ANONYMOUS
+# define zero_fd -1
+# define map_flags MAP_ANONYMOUS | MAP_PRIVATE
+#elif HAVE_MMAP_DEVZERO
+static int zero_fd;
+# define map_flags MAP_FILE | MAP_PRIVATE
+#endif
+unsigned long page;
+int handler_called = 0;
+void sigsegv_handler (int sig, siginfo_t *sip, void *ucp)
+{
+  void *fault_address = (void *) (sip->si_ptr);
+  handler_called++;
+  if (fault_address != (void*)(page + 0x678))
+    exit (3);
+  if (mprotect ((void *) page, 0x10000, PROT_READ | PROT_WRITE) < 0)
+    exit (2);
+}
+void crasher (unsigned long p)
+{
+  *(int *) (p + 0x678) = 42;
+}
+int main ()
+{
+  void *p;
+  struct sigaction action;
+  /* Preparations.  */
+#if !HAVE_MMAP_ANON && !HAVE_MMAP_ANONYMOUS && HAVE_MMAP_DEVZERO
+  zero_fd = open ("/dev/zero", O_RDONLY, 0644);
+#endif
+  /* Setup some mmaped memory.  */
+#ifdef __hpux
+  /* HP-UX 10 mmap() often fails when given a hint.  So give the OS complete
+     freedom about the address range.  */
+  p = mmap ((void *) 0,          0x10000, PROT_READ | PROT_WRITE, map_flags, zero_fd, 0);
+#else
+  p = mmap ((void *) 0x12340000, 0x10000, PROT_READ | PROT_WRITE, map_flags, zero_fd, 0);
+#endif
+  if (p == (void *)(-1))
+    exit (2);
+  page = (unsigned long) p;
+  /* Make it read-only.  */
+  if (mprotect ((void *) page, 0x10000, PROT_READ) < 0)
+    exit (2);
+  /* Install the SIGSEGV handler.  */
+  sigemptyset(&action.sa_mask);
+action.sa_sigaction = &sigsegv_handler;
+   action.sa_flags = SA_SIGINFO;
+  sigaction (SIGSEGV, &action, (struct sigaction *) NULL);
+  sigaction (SIGBUS, &action, (struct sigaction *) NULL);
+  /* The first write access should invoke the handler and then complete.  */
+  crasher (page);
+  /* The second write access should not invoke the handler.  */
+  crasher (page);
+  /* Check that the handler was called only once.  */
+  if (handler_called != 1)
+    exit (1);
+  /* Test passed!  */
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sv_cv_fault_linux_hppa=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+sv_cv_fault_linux_hppa=no
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+fi
+echo "$as_me:$LINENO: result: $sv_cv_fault_linux_hppa" >&5
+echo "${ECHO_T}$sv_cv_fault_linux_hppa" >&6
+
+
+
+
+
+
   echo "$as_me:$LINENO: checking whether a fault handler according to BSD works" >&5
 echo $ECHO_N "checking whether a fault handler according to BSD works... $ECHO_C" >&6
 if test "${sv_cv_fault_bsd+set}" = set; then
@@ -10048,7 +10228,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 #include <signal.h>
 
 #define USE_64BIT_REGS(mc) \
-  (((mc).ss_flags & SS_WIDEREGS) && ((mc).ss_flags & SS_NARROWISINVALID)
+  (((mc).ss_flags & SS_WIDEREGS) && ((mc).ss_flags & SS_NARROWISINVALID))
 #define GET_CR21(mc) \
   (USE_64BIT_REGS(mc) ? (mc).ss_wide.ss_64.ss_cr21 : (mc).ss_narrow.ss_cr21)
 
@@ -10105,7 +10285,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 #endif
 
 #define USE_64BIT_REGS(mc) \
-  (((mc).ss_flags & SS_WIDEREGS) && ((mc).ss_flags & SS_NARROWISINVALID)
+  (((mc).ss_flags & SS_WIDEREGS) && ((mc).ss_flags & SS_NARROWISINVALID))
 #define GET_CR21(mc) \
   (USE_64BIT_REGS(mc) ? (mc).ss_wide.ss_64.ss_cr21 : (mc).ss_narrow.ss_cr21)
 
@@ -10987,9 +11167,20 @@ if test -z "$CFG_FAULT" && test "$sv_cv_fault_linux_powerpc" = yes; then
   esac
   FAULT_CONTEXT='struct sigcontext'
 fi
+if test -z "$CFG_FAULT" && test "$sv_cv_fault_linux_hppa" = yes; then
+  case "$host_cpu" in
+    hppa* | parisc*) CFG_FAULT=fault-linux-hppa.h ;;
+  esac
+fi
 if test -z "$CFG_FAULT" && test "$sv_cv_fault_hurd" = yes; then
-  CFG_FAULT=fault-hurd.h
-  FAULT_CONTEXT='struct sigcontext'
+  case "$host_os" in
+    netbsd*) # A false positive.
+      ;;
+    *)
+      CFG_FAULT=fault-hurd.h
+      FAULT_CONTEXT='struct sigcontext'
+      ;;
+  esac
 fi
 if test -z "$CFG_FAULT" && test "$sv_cv_fault_bsd" = yes; then
   case "$host_os" in
@@ -11013,19 +11204,30 @@ if test -z "$CFG_FAULT" && test "$sv_cv_fault_bsd" = yes; then
 fi
 if test -z "$CFG_FAULT" && test "$sv_cv_fault_posix" = yes; then
   case "$host_os" in
-    solaris*)
+    openbsd*)
       case "$host_cpu" in
-        i?86 | x86_64) CFG_FAULT=fault-solaris-i386.h ;;
-        sparc*) CFG_FAULT=fault-solaris-sparc.h ;;
-        *) CFG_FAULT=fault-solaris.h ;;
+        i?86 | x86_64) CFG_FAULT=fault-openbsd-i386.h ;;
+        *) CFG_FAULT=fault-openbsd.h ;;
       esac
+      FAULT_CONTEXT='struct sigcontext'
       ;;
     *)
-      CFG_FAULT=fault-posix.h
+      case "$host_os" in
+        solaris*)
+          case "$host_cpu" in
+            i?86 | x86_64) CFG_FAULT=fault-solaris-i386.h ;;
+            sparc*) CFG_FAULT=fault-solaris-sparc.h ;;
+            *) CFG_FAULT=fault-solaris.h ;;
+          esac
+          ;;
+        *)
+          CFG_FAULT=fault-posix.h
+          ;;
+      esac
+      FAULT_CONTEXT='ucontext_t'
+      FAULT_CONTEXT_INCLUDE='#include <ucontext.h>'
       ;;
   esac
-  FAULT_CONTEXT='ucontext_t'
-  FAULT_CONTEXT_INCLUDE='#include <ucontext.h>'
 fi
 if test -z "$CFG_FAULT" && test "$sv_cv_fault_linux_m68k" = yes; then
   case "$host_cpu" in
@@ -11070,11 +11272,6 @@ else
         cris)
           CFG_FAULT=fault-linux-cris.h
           FAULT_CONTEXT='struct sigcontext'
-          ;;
-        hppa* | parisc*)
-          CFG_FAULT=fault-linux-hppa.h
-          FAULT_CONTEXT='ucontext_t'
-          FAULT_CONTEXT_INCLUDE='#include <ucontext.h>'
           ;;
         ia64)
           CFG_FAULT=fault-linux-ia64.h
